### ISSUE TITLE
Working with seed?

### ISSUE THREAD

**Issue by Firlefanz** [devedse/DeveMazeGenerator#1]
Hello,

can I create the same maze again using the same seed, does it Support seeds?

Is it possible to make a real 3D maze with it? And does it Need to be stored in an Array or somethin or can it be just initialized then asked for an empty part something like "IsEmpty(x,y,z)"?

Interesting stuff and impressive size and Speed :-)

**Comment by devedse** [comment]
Hi Firlefanz,

Yes seeds are supported, I'm currently working on a new version of my Maze generator written in dotnet core (using a different interface though), so if you can, I would advise you to use that:
[devedse/devemazeGeneratorCore](http://github.com/devedse/devemazeGeneratorCore)

Anyway, an example how to use a seed with my DotNet core Maze generator: https://github.com/devedse/DeveMazeGeneratorCore/blob/master/test/DeveMazeGenerator.Tests/Generators/MazeSamples.cs

3D mazes are not supported though. Only a 3D visualization of a 2D maze.

If you have any more questions, let me know :)
